sudo: required

services:
    - docker

language: go

env:
    global:
        - COMMIT=${TRAVIS_COMMIT::8}

after_success:
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    - export PFX=indeedoss/imhotep-
    - export OS=centos6

    - export IMG=base-java7
    - cd $TRAVIS_BUILD_DIR/$IMG/$OS && docker build -t $PFX$IMG:$COMMIT .
    - docker tag $PFX$IMG $PFX$IMG:$TAG
    - docker tag $PFX$IMG:$COMMIT $PFX$IMG:travis-$TRAVIS_BUILD_NUMBER
    - docker push $PFX$IMG

    - export IMG=zookeeper
    - cd $TRAVIS_BUILD_DIR/$IMG/$OS && docker build -t $PFX$IMG:$COMMIT .
    - docker tag $PFX$IMG $PFX$IMG:$TAG
    - docker tag $PFX$IMG:$COMMIT $PFX$IMG:travis-$TRAVIS_BUILD_NUMBER
    - docker push $PFX$IMG

    - export IMG=cdh5-hdfs
    - cd $TRAVIS_BUILD_DIR/$IMG/$OS && docker build -t $PFX$IMG:$COMMIT .
    - docker tag $PFX$IMG $PFX$IMG:$TAG
    - docker tag $PFX$IMG:$COMMIT $PFX$IMG:travis-$TRAVIS_BUILD_NUMBER
    - docker push $PFX$IMG

    - export IMG=daemon
    - cd $TRAVIS_BUILD_DIR/$IMG/$OS && docker build -t $PFX$IMG:$COMMIT .
    - docker tag $PFX$IMG $PFX$IMG:$TAG
    - docker tag $PFX$IMG:$COMMIT $PFX$IMG:travis-$TRAVIS_BUILD_NUMBER
    - docker push $PFX$IMG

    - export IMG=frontend
    - cd $TRAVIS_BUILD_DIR/$IMG/$OS && docker build -t $PFX$IMG:$COMMIT .
    - docker tag $PFX$IMG $PFX$IMG:$TAG
    - docker tag $PFX$IMG:$COMMIT $PFX$IMG:travis-$TRAVIS_BUILD_NUMBER
    - docker push $PFX$IMG

