version: '2'

volumes:
    hdfs-data:

services:
    hadoop:
        image: local/imhotep-cdh5-hdfs:centos6
        volumes:
            - 'hdfs-data:/var/lib/hadoop-hdfs'
        expose:
            - "8020"
    zookeeper:
        image: local/imhotep-zookeeper:centos6
        expose:
            - "2181"
    daemon:
        image: local/imhotep-daemon:centos6
        expose:
            - "12345"
    frontend:
        image: local/imhotep-frontend:centos6
        ports:
         - "${IQL_PORT}:80"
