version: '2'

volumes:
    hdfs-data:

services:
    hadoop:
        image: indeedoss/imhotep-cdh5-hdfs:latest
        volumes:
            - 'hdfs-data:/var/lib/hadoop-hdfs'
        expose:
            - "8020"
    zookeeper:
        image: indeedoss/imhotep-zookeeper:latest
        expose:
            - "2181"
    daemon:
        image: indeedoss/imhotep-daemon:latest
        expose:
            - "12345"
    frontend:
        image: indeedoss/imhotep-frontend:latest
        ports:
         - "${IQL_PORT}:80"
