version: '2'

volumes:
    hdfs-data:

services:
    hadoop:
        #build: hadoop
        image: imhotep-cdh5-hdfs
        volumes:
            - 'hdfs-data:/var/lib/hadoop-hdfs'
        expose:
            - "8020"
    zookeeper:
        #build: zookeeper
        image: imhotep-zookeeper
        expose:
            - "2181"
        #ports:
        # - "2181:2181"
        #network_mode: "host"
    daemon:
        #build: daemon
        image: imhotep-daemon
        expose:
            - "12345"
        #ports:
        # - "12345:12345"
        #network_mode: "host"
    frontend:
        #build: frontend
        image: imhotep-frontend
        ports:
         - "${IQL_PORT}:80"
        #network_mode: "host"
